### PR TITLE
Add format and value controls for UTC Offset

### PR DESCRIPTION
**Pull request by se98100**
**ISSUE #4 B**
For now I implemented the control with the `:` notation and implemented the conversion to the `.` notation to pass the value to the backend.
I also modified the input's width to allow all the possible offsets to be shown completely.
I took as reference this Wikipedia's [page](https://en.wikipedia.org/wiki/List_of_UTC_time_offsets) for the correct offsets.

### CODE REVIEW

**Comment by se98100** [comment]
I forgot to change a couple of things, give me some time to correct them, sorry.

**Comment by se98100** [comment]
Now everything should be fine.
The way I implemented the control does never allow for an incorrect offset to be present in the input therefore assuming, for example, the current value is `+12:45` and you want to change it to `+12`, you cannot delete the `5`, `4` and `:` in sequence but you would have to select the 3 char and delete them together in order to accomplish this. Just try it :)

**Comment by DenverCoder1** [comment]
👍 It seems to be working

One thing I noticed is that for most numbers it doesn't allow leaving a `:` at the end (ex. `+4:`) but with 5, it does allow it (ex. `+5:`). I guess that can't really be prevented because you can't predict whether 30 or 45 will come afterwards.

I think it's cool that it only allows valid input for the most part, but I think updating on every key press is a bit too aggressive possibly. Like you said, you can't delete 45 if it gets added to the input without deleting it all at once. This could be difficult for some users to figure out. Maybe it would be better to have it do the strict validation onBlur and a more lenient validation on key press (like just checking that it's in the form to possibly be the beginning of a timezone input) and let it fix it only when you click somewhere else?

What are your thoughts on that?

**Comment by se98100** [comment]
I agree on the fact that it could have been not very intuitive, instead I am very satisfied with the version I just committed.
What do you think about it?

**Comment by DenverCoder1** [comment]
👍 Looks great! Is it ready to be merged?

**Comment by se98100** [comment]
Yes :)

**Comment by DenverCoder1** [comment]
Thanks! Changes were merged and the website has been updated.

**Pull request merged**
