### PR TITLE
Apply control to timezone input in countdown page

### PR DESCRIPTION
**Pull request by se98100**
**ISSUE #4 C**
I applied the control to the timezone input in the countdown page and modified the way changes are applied to support the `:` notation.

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Looks great.

There seems to be an issue when the timezone is set, though. It should update the countdown date to display in the selected timezone, but it seems to no longer change.

**Comment by DenverCoder1** [comment]
`timezoneDiff` should be set to the selected timezone as a floating point number before calling `setLocalDate()`

**Comment by se98100** [comment]
This should fix the issue 👍

**Comment by DenverCoder1** [comment]
👍 Merged!

**Pull request merged**
