### PR TITLE
Fix UI responsive issue on smaller screens

### PR DESCRIPTION
**Pull request by tharindulucky**
### Fixed the UI responsive issue on smaller screens.

Added new CSS rules to the current media quires, changed some width and font-sizes (All as a percentage). I didn't change the device breakpoints though. 

Now the responsive issue is fixed on all devices. 

### Smaller screens (iPhone 5 SE)
image

### Small screens (Pixel 2 XL)
image

### Medium screens (iPad pro)
image

### Bigger screens (Desktop)
image

I'd appreciate if you could review this and merge if no issues. Please let me know if any clarifications or changes required.

And also, if this PR meets your standards, kindly label this as `hacktoberfest-accepted`

### CODE REVIEW

**Comment by DenverCoder1** [comment]
👍 Awesome! This is a very good PR.

For mobile I was thinking it should look something like the image below so that the text doesn't get too small.

That's why in the media query for under 500px, the countdown divs were set to 40% (it can possibly be made higher to space them out more). Would you be able to adjust the widths and sizes to be bigger on mobile?

image

**Comment by tharindulucky** [comment]
Yeah, sure! I'll make the adjustment.

**Comment by tharindulucky** [comment]
@DenverCoder1 I made the adjustment on the mobile screens as you instructed. 

Now the mobile screens will look like this..

**iPhone X**
image

**Pixel 2**
image

Is this fine for you ? Let me know what you think!

**Comment by DenverCoder1** [comment]
👍 Amazing!

Looks great! I will merge these changes.

**Comment by tharindulucky** [comment]
Happy to help!

**Pull request merged**
